api_query_interval: 0.0
dataset_name: ScalingIntelligence/KernelBench
dataset_src: huggingface
level: 1
log_prompt: false
max_tokens: 32768
model_name: gemini-2.5-pro
num_workers: 8
run_name: gemini_level1_run
runs_dir: /home/ubuntu/KernelBench/runs
server_type: google
store_type: local
subset:
- null
- null
temperature: 0
verbose: false
